# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fac9f8cf8283aee28306dc6af7d2d84f9cc8e2dc78e8cf9e65d13e94e2e0d2e0591e3cf597b9508e3149fa9be2510b6b2c4357f2e4748abb00f2f69edcb4b973

test:
  secret_key_base: b52e39fe59cae86e0a9122fac04026f4ab6abd41d0a9cd7a27c260a11f23f141748a4f8b11f8040c6114d8a61a3b96685f2630b27e8b746a72fd34515523eb44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
